Performance calculation service
Panoptimize/BackEnd pull request #100
Opened 2024-05-26 19:26 UTC by EstherRC

2024-05-27 17:28 UTC, ErnoMitrovic commented on src/main/java/com/itesm/panoptimize/config/GlobalCorsConfig.java
Después lo cambiamos 👍

2024-05-27 17:30 UTC, ErnoMitrovic requested changes

2024-05-27 17:30 UTC, ErnoMitrovic commented on .DS_Store
No binarios

2024-05-27 17:30 UTC, ErnoMitrovic commented on src/main/java/com/itesm/panoptimize/model/Contact.java
Por qué el contacto está como Long?

2024-05-28 00:57 UTC, Raul-VR reviewed
coool

2024-05-28 00:57 UTC, Raul-VR approved these changes
cool!

2024-05-28 01:20 UTC, ErnoMitrovic approved these changes

2024-05-28 01:45 UTC, merged