First Response Contact KPI
Panoptimize/BackEnd pull request #66
Opened 2024-04-30 18:44 UTC by lunarmelon

2024-04-30 19:27 UTC, ErnoMitrovic requested changes

2024-04-30 19:27 UTC, ErnoMitrovic commented on src/main/java/com/itesm/panoptimize/controller/DashboardController.java
API_URL se puede usar como una variable de entorno

2024-04-30 19:27 UTC, ErnoMitrovic commented on src/main/java/com/itesm/panoptimize/controller/DashboardController.java
Si me puedes cambiar el endpoint para que se llame FCR sería mejor (o algo parecido)

2024-05-01 19:06 UTC, BillySh commented on src/main/java/com/itesm/panoptimize/controller/DashboardController.java
La quieres como variable de entorno?

2024-05-01 19:07 UTC, BillySh commented on src/main/java/com/itesm/panoptimize/controller/DashboardController.java
El de metrics?

2024-05-01 19:16 UTC, BillySh commented on src/main/java/com/itesm/panoptimize/controller/DashboardController.java
Ya cambié ese.

2024-05-01 23:05 UTC, ErnoMitrovic approved these changes

2024-05-02 05:16 UTC, merged